jobs:
- job: MeasureDevRandomSpeed
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: 'dd if=/dev/random bs=1000 count=10 > /dev/null'
- job: MeasureDevUrandomSpeed
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - bash: 'dd if=/dev/urandom bs=1M count=10 > /dev/null'
